- blog/source/_drafts/Easily-Creating-An-Online-Battleship-with-Boardgame-io.md
Improve the grammar of Easily-Creating-An-Online-Battleship-with-Boardgame-io.md.
> Improve Easily-Creating-An-Online-Battleship-with-Boardgame-io.md

- @types/boardgame.io/index.d.ts
- package.json
- src/components/games/battleship/game.test.ts
- src/components/games/battleship/game.ts
- src/components/games/chess/game.test.ts
- src/components/games/chess/game.ts
- src/node.d.ts
- tsconfig.json
Implementing the "set ship" action for the battleship game logic.
> Implements setShips

- package-lock.json
- package.json
Installs git precommit hook using https://www.npmjs.com/package/pre-commit
Tests before committing (use --no-verify to override).
> Installs git precommit hook for testing before committing

- package-lock.json
- src/App/Game/GameSharing.tsx
Tested with both seabattle and chess.
> Dismiss sharing window after copying link to clipboard

- package.json
- tsconfig.json
- yarn.lock
I use tslint-language-service this for my Vim setup.
> Add tslint-language-service dev dependency

- Dockerfile
- README.md
- docker-compose.yml
Add Dockerfile, docker-compose.yml
> Add Dockerfile, docker-compose.yml

- src/About/About.test.tsx
- src/About/About.tsx
- src/App/App.tsx
- src/Home/Home.tsx
- Add /about page
This PR closes #71
> Add /about

- src/App/FreeBoardGameBar.test.tsx
- src/App/FreeBoardGameBar.tsx
- src/App/Game/Game.test.tsx
- src/App/Game/GameDarkSublayout.test.tsx
- src/App/Game/GameDarkSublayout.tsx
- src/App/Game/GameInfo.test.tsx
- src/App/Game/GameInfo.tsx
- src/App/Game/GameModePicker.test.tsx
- src/App/Game/GameModePicker.tsx
- src/App/GamesList.tsx
- src/games/chess/board.test.tsx
- src/games/seabattle/ShipsPlacement.test.tsx
- src/games/seabattle/board.test.tsx
> Using <Link to= instead of <a

- src/App/Game/GameSharing.tsx
Fix #107 by showing all share icons on one row.
> Fix #107 by showing all share icons on one row

- webpack.common.js
Add navigateFallbackBlacklist so /blog* isn't cached by the service worker
> Add navigateFallbackBlacklist for /blog*

- src/games/chess/board.tsx
> Fixing chess not loading state issue

- static/robots.txt
> robots.txt: forbid crawling

- README.md
- src/App/GamesList.tsx
- src/Home/Header.test.tsx
- src/Home/Header.tsx
- src/Home/Home.tsx
* Add link to Discord
* Move many links up on the homepage as material-ui logos
> Homepage links

- webpack.common.js
navigateFallBackBlacklist: exclude .txt and .xml files (robots.txt, sitemap.xml)
> navigateFallBackBlacklist: exclude .txt and .xml files

- src/App/MessagePage.tsx
- src/App/MessagePageClass.test.tsx
- src/App/MessagePageClass.tsx
Working on MessagePage to have a more obvious link to go home in case of an error or a loading timeout (loading for > 5 seconds).
> MessagePage: add user-friendly link to go home in the case of an error or a loading timeout (loading for > 5 seconds)

- src/metadata.test.ts
- src/metadata.ts
Improve metadata descriptions, fix problem with Seabattle's description (more specific URLs must come first), add more tests.
> Improve metadata descriptions, fix problem with Seabattle's description, add more tests

- src/App/Game/Game.test.tsx
- src/App/Game/Game.tsx
- src/App/Game/GameInfo.test.tsx
- src/App/Game/GameInfo.tsx
Fix #132 by showing an error message when browsing to an unknown gamecode
> Show an error message when browsing to an unknown gamecode

- src/App/FreeBoardGameBar.tsx
- src/index.html
- src/server.tsx
- static/manifest.json
- webpack.common.js
> Making app bar sticky and matching theme color with app bar color

- @types/koa-no-cache/index.d.ts
- package.json
- src/server.tsx
- yarn.lock
Add koa-no-cache to try to fix our index.html caching problem (the service worker will take care of caching pages)
> Add koa-no-cache to fix caching problem

- src/server.tsx
- webpack.common.js
Fix workbox caching, networkFirst for mp3/png/js files, rename template2.html to template.html
> Fix workbox caching, networkFirst for mp3/png/js files, rename template2.html to template.html

- src/App/Game/Game.test.tsx
- src/App/Game/Game.tsx
This should fix a 500 when SSR attempts to render a page with an unknown gameCode (such as https://freeboardgame.org/g/blah/online/duWXPMU_J7/0 )
> Load only if this.gameDef is defined

- src/App/MessagePageClass.tsx
> Fix serverside rendering

- package.json
Add `yarn run autopre[commit]` to autoformat files then run tests
> Add `yarn run autopre[commit]` to autoformat files then run tests

- src/App/Game/GameOver.tsx
> Center gameover text

- package.json
- yarn.lock
Fix problems with jest on node v11.11.0 by upgrading (fixes #157).
> Fix problems with jest on node v11.11.0 by upgrading

- README.md
Fix build status badge in README.md by changing to Semaphore's badge
> Fix build status badge in README.md

- @types/@freeboardgame.org/index.d.ts
- src/games/index.tsx
- src/games/tictactoe/ai.test.ts
- src/games/tictactoe/ai.ts
- src/games/tictactoe/board.test.tsx
- src/games/tictactoe/board.tsx
> Add Tic Tac Toe AI

- src/App/Game/GameLayout.test.tsx
- src/App/Game/GameLayout.tsx
- src/App/Game/GameOver.tsx
- src/games/chess/board.tsx
- src/games/tictactoe/board.tsx
Add 'play again' button for local/AI games
---
> Add 'play again' button for local/AI games

- src/games/seabattle/game.test.tsx
- src/games/seabattle/game.ts
- src/games/seabattle/mocks.ts
Give each ship a unique ID (to be used in a future seabattle AI PR).
> Give each ship a unique ID

- src/games/tictactoe/ai.ts
Use player ID for tictactoe AI (so simulate works)
> Use player ID for tictactoe AI (so simulate works)

- src/games/tictactoe/ai.ts
Improve TicTacToe easy AI efficiency by not randomly guessing cells
> Improve TicTacToe easy AI

- src/games/seabattle/Battle.test.tsx
> Fix typo in Battle.test.tsx

- src/games/seabattle/Radar.test.tsx
Add id attribute to ships in Radar.test.tsx (will fix unique key prop warnings)
> Add id attribute to ships in Radar.test.tsx (will fix unique key prop warnings)

- src/App/Game/Game.test.tsx
Increase coverage in games/index.ts by testing all games with their applicable modes
> Increase coverage in games/index.ts

- src/games/tictactoe/board.test.tsx
- src/games/tictactoe/board.tsx
When playing a TicTacToe AI game, show "you won/you lost"
> When playing a TicTacToe AI game, show "you won/you lost"

- src/games/chess/board.test.tsx
- src/games/chess/board.tsx
Chess: when playing an AI game, show you won/you lost at gameover
> Chess: when playing an AI game, show you won/you lost at gameover

- src/App/Game/GameOver.tsx
- src/games/chess/board.test.tsx
- src/games/seabattle/board.test.tsx
- src/games/seabattle/board.tsx
- src/games/tictactoe/board.test.tsx
> Add analytics to GameOver

- src/games/tictactoe/ai.ts
Avoid returning undefined in TicTacToe easy AI
> Avoid returning undefined in TicTacToe easy AI 

- src/games/seabattle/Battle.tsx
> Reduce seabattle AI delay

- src/App/Game/GameSharing.tsx
Add gameCode label for analytics to GameSharing
> Add gameCode label for analytics to GameSharing

- package.json
- yarn.lock
Add mongo to package.json for MongoDB
> Add mongo to package.json for MongoDB

- src/App/Game/Game.tsx
- src/games/seabattle/config.ts
- src/games/seabattle/sound.test.ts
- src/games/seabattle/sound.ts
Tests are currently failing and I am not sure of an elegant way to fix... @flamecoals ?
Will fix #188
> Get sound working in Seabattle's AI mode

- src/App/Game/Game.tsx
- src/games/index.tsx
- src/games/seabattle/config.ts
Support multiple enhancers passed as an array in config
> Support multiple enhancers passed as an array in config

- src/games/seabattle/board.tsx
Fix Seabattle's endgame by showing the other player's ships at gameover
> Fix Seabattle's Endgame

- src/games/chess/board.tsx
- src/games/chess/checkerboard.test.tsx
- src/games/chess/checkerboard.tsx
> Adding drag and drop to chess

- src/App/Game/Game.tsx
- src/games/chess/board.tsx
Fix local games.  
In chess, unhighlight last square after making a move.
Fixes #207
> Fix local games / in chess, unhighlight last square after making a move

- src/metadata.test.ts
Increase metadata.ts test coverage
> Increase metadata.ts test coverage

- src/App/Game/Game.tsx
Set playerID to '0' by default
Fixes #216
> Set playerID to '0' by default

- src/App/Game/Enhancers/ReactGAEnhancer.ts
- src/App/Game/Enhancers/index.ts
- src/App/Game/Game.tsx
- src/games/chess/board.tsx
Closes #63 
* Automatic GA event tracking for all games
* Remove GA from Chess (no longer needed)
> Automatic GA event tracking for all games

- @types/react-easy-i18n/index.d.ts
- package.json
- src/About/About.tsx
- src/App/App.ssr.test.tsx
- src/App/App.tsx
- src/App/translations/en.ts
- src/App/translations/index.ts
- test/test-setup.js
- yarn.lock
Add working i18n :-)
This PR is just laying out the framework for i18n.  We can add translations for pages / games in separate PRs.
> Add working i18n!

- src/App/App.test.tsx
- src/App/App.tsx
- src/App/MessagePageClass.test.tsx
- src/App/MessagePageClass.tsx
- src/App/translations/en.ts
- src/App/translations/index.ts
- src/App/translations/pt.ts
* Add URL-based language selector, default to English
* Begin work on PT translations (mainly to show i18n logic)
* @flamecoals, you can probably do the PT translations better than I can :-p
* Switch MessagePage to use i18n text
* Update tests accordingly
> Add URL-based language selector

- src/App/App.tsx
- src/App/translations/en.ts
Show error message, return 404, for invalid locales
> Show error message, return 404, for invalid locales

- src/App/App.test.tsx
- src/App/App.tsx
- src/App/MessagePageClass.tsx
- src/App/translations/en.ts
Do not automatically translate messagePage (perhaps revisit in the future when better support for translations is implemented)
> Do not automatically translate messagePage

- package.json
Exclude servers from test coverage
> Exclude servers from test coverage

- package.json
- webpack.dev.js
- webpack.server.js
- yarn.lock
Remove hard-source-webpack-plugin -- possibly causing issues with 404's
> Remove hard-source-webpack-plugin -- possibly causing issues with 404's

- @types/@freeboardgame.org/index.d.ts
Typescript definition for https://boardgame.io/#/secret-state
> Define STRIP_SECRETS

- @types/@freeboardgame.org/index.d.ts
- src/games/chess/game.ts
As shown here https://boardgame.io/#/turn-order?id=implementing-a-custom-turn-order
> Definition for custom implementation of turn order, randomness and fixes

- webpack.common.js
Split more chunks with webpack
> Split more chunks with webpack

- @types/@freeboardgame.org/index.d.ts
- @types/ts-easy-i18n/index.d.ts
- package.json
- src/About/About.tsx
- src/App/App.tsx
- src/App/MessagePageClass.tsx
- src/App/translations/cs.ts
- test/test-setup.js
- yarn.lock
Better i18n with fallback to English
> Better i18n with fallback to English

- src/App/Game/GameOver.tsx
> Move extraCardContent to better position

- src/App/Game/GameModePicker.test.tsx
- src/App/Lobby/ListPlayers.tsx
- src/App/Lobby/NicknamePrompt.tsx
- src/App/Lobby/Room.tsx
Move nickname prompt into its own component
> Move nickname prompt into its own component

- src/App/Lobby/NicknamePrompt.tsx
- src/App/Lobby/Room.tsx
Allow users to close the name prompt when they are editing their name
> Allow users to close the name prompt when they are editing their name

- src/App/Lobby/QrCodePopup.tsx
Add clickawaylistener to qrcodes
> Add clickawaylistener to qrcodes

- src/About/About.tsx
- src/App/translations/cs.ts
- src/App/translations/en.ts
- src/App/translations/pt.ts
> Add more i18n

- package.json
- yarn.lock
Fix yarn.lock from dependabot/npm_and_yarn/handlebars-4.1.2 #261, upgrade deps
> Fix yarn.lock from dependabot/npm_and_yarn/handlebars-4.1.2 #261, upgrade deps

- @types/@freeboardgame.org/index.d.ts
- @types/chess.js/index.d.ts
- @types/koa-no-cache/index.d.ts
- @types/static.d.ts
- package.json
> Format @types/

- package.json
- yarn.lock
Upgrade packages in package.json
> Upgrade packages in package.json

- src/metadata.test.ts
- src/metadata.ts
> Improve metadata

- src/App/App.tsx
- src/App/FreeBoardGameBar.tsx
- src/App/Game/GameDarkSublayout.tsx
- src/App/Game/GameModePicker.tsx
- src/App/Game/GameOver.tsx
- src/App/Game/GameSharing.tsx
- src/App/GamesList.tsx
- src/App/Lobby/NicknamePrompt.tsx
- src/App/MessagePageClass.tsx
- src/Home/Header.tsx
- src/games/seabattle/board.tsx
- src/games/takesix/board.test.tsx
Fix a lot of console errors/warnings related to material-ui and components 
Improving (but did not completely fix) #95
> Fix a lot of console errors/warnings related to material-ui and components 

- src/App/Game/GameDarkSublayout.tsx
> Fix typography variant

- src/App/Game/GameOver.tsx
- src/games/takesix/Decks.tsx
- src/games/takesix/ai.ts
- src/games/takesix/board.tsx
- src/games/takesix/game.ts
> Fix takeSix bug when clicking where it shouldnt in AI. 

- webpack.common.js
https://github.com/webpack/webpack/issues/6642
> Fix webpack hot reload bug

- src/index.html
Remove comment from index.html
> Remove comment from index.html

- package.json
- yarn.lock
Add Husky for pre-commit tests
> Add Husky for pre-commit tests

- src/games/tictactoe/index.ts
- src/typings.d.ts
- webpack.common.js
- webpack.server.js
Import markdown files directly
> Import markdown files directly

- src/games/takesix/game.test.ts
Rename TictactoeCustomScenario  -> TakesixCustomScenario
> Rename TictactoeCustomScenario  -> TakesixCustomScenario 

- src/App/Game/GameInstructions.tsx
- src/games/chess/index.ts
- src/games/chess/instructions.md
- src/games/tictactoe/index.ts
- src/typings.d.ts
- webpack.common.js
- webpack.server.js
Add text instructions to Chess
> Add text instructions to Chess

- src/games/seabattle/index.ts
- src/games/seabattle/instructions.md
Add Seabattle text instructions
> Add Seabattle text instructions

- README.md
Add Nine Mens Morris to README
>  Add Nine Mens Morris to README

- src/App/App.tsx
> Use SSRHelper.isSSR() in App.tsx

- blog/themes/next/layout/_partials/header.swig
Make FreeBoardGame.org link in blog go to /
> Make FreeBoardGame.org link in blog go to /

- src/games/index.ts
> Change order of games

- src/games/reversi/Scoreboard.tsx
reversi: penalty points -> score points
> reversi: penalty points -> score points

- src/games/reversi/ScoreBadges.css
- src/games/reversi/ScoreBadges.tsx
- src/games/reversi/board.tsx
- src/games/reversi/game.ts
> Badges [Reversi]

- src/index.html
- src/metadata.ts
- src/server_fbg.tsx
Add breadcrumbs support for SEO
https://developers.google.com/search/docs/data-types/breadcrumb
> Add breadcrumbs support for SEO

- src/app.tsx
> Enable full hot reloading

- src/index.html
- src/server_fbg.tsx
Format html, update server_fbg.tsx accordingly
> Format html, update server_fbg.tsx accordingly

- package.json
- src/App/App.ssr.test.tsx
- src/App/App.test.tsx
- yarn.lock
Fix App.test.tsx (was actually testing our async loading page, not App.tsx...), increase coverage
> Fix App.test.tsx (was actually testing our async loading page, not App.tsx...), increase coverage

- src/App/Lobby/LobbyService.test.tsx
> Test lobby rename

- package.json
- src/App/App.test.tsx
- yarn.lock
Use setImmediate() instead of wait-for-expect in App.test.tsx
> Use setImmediate() instead of wait-for-expect in App.test.tsx

- package.json
> Fix precommit hook

- blog/source/_posts/Publishing-your-first-boardgame-io-game-in-FBG.md
I will de-prioritizing adding checkers, as it is a game that has high availability online already, and it is more complex to code it right than it seems (I did not find a good library with checkers rules).
> Remove checkers reference from blog post

- src/App/App.ssr.test.tsx
- src/App/Lobby/ListPlayers.tsx
- src/App/Lobby/Room.test.tsx
- src/App/Lobby/Room.tsx
Increase test coverage in Room.tsx
> Increase test coverage in Room.tsx

- src/App/Lobby/NicknamePrompt.test.tsx
> Add NicknamePrompt.test.tsx

- package.json
- yarn.lock
Upgrade react-markdown to 4.1.0
> Upgrade react-markdown to 4.1.0

- package.json
Move @types/enzyme to devDependencies
> Move @types/enzyme to devDependencies

- package.json
- yarn.lock
> Upgrade husky to 2.7.0

- package.json
- yarn.lock
> Upgrade superagent to 5.1.0

- package.json
- yarn.lock
> Upgrade react-ga to 2.6.0

- package.json
Improve husky precommit hook, do not auto fix (so to be more similar to CI)
>  Improve husky precommit hook, do not auto fix (so to be more similar to CI)

- package.json
> CI: treat warnings as errors

- src/App/Game/Enhancers/ReactGAEnhancer.test.ts
Increase coverage for ReactGAEnhancer.ts
> Increase coverage for ReactGAEnhancer.ts

- package.json
> Fix CI / format:check

- src/App/MessagePageClass.test.tsx
Increase coverage for MessagePageClass
> Increase coverage for MessagePageClass

- src/App/Lobby/LobbyService.test.tsx
- src/App/Lobby/LobbyService.ts
Increase coverage for LobbyService
> Increase coverage for LobbyService

- src/metadata.test.ts
Increase coverage for metadata
> Increase coverage for metadata

- src/App/Game/GameBoardWrapper.test.tsx
- src/App/Game/GameBoardWrapper.tsx
Increase coverage for GameBoardWrapper
> Increase coverage for GameBoardWrapper

- .eslintrc.js
- src/App/Lobby/ListPlayers.tsx
- src/games/seabattle/Radar.tsx
Add eslint rule: react/no-unused-state
> Add eslint rule: react/no-unused-state

- src/App/Game/GameSharing.test.tsx
> Add GameSharing.test.tsx

- package.json
- yarn.lock
> Upgrade webpack to 4.35.2

- Dockerfile
Improve Dockerfile, take advantage of caching
> Improve Dockerfile, take advantage of caching

- src/App/Game/Game.test.tsx
- src/App/Game/Game.tsx
Increase coverage for Game.tsx
> Increase coverage for Game.tsx

- .dockerignore
- .gitignore
- package.json
- webpack.dev.js
- webpack.server.js
Use dist/ and server-dist/ (instead of server-build/) for uniformity
> Use dist/ and server-dist/ (instead of server-build/) for uniformity

- package.json
- yarn.lock
> Upgrade babel and ts-loader

- .dockerignore
- Dockerfile
Docker: upgrade node version, add to .dockerignore
> Docker: upgrade node version, add to .dockerignore

- src/games/chess/index.ts
- src/games/ninemensmorris/index.ts
- src/games/takesix/index.ts
- src/games/tictactoe/index.ts
- src/metadata.ts
> Use description in title

- src/server_fbg.tsx
- static/.well-known/assetlinks.json
Add static/.well-known/assetlinks.json (for FBG Android app)
> Add static/.well-known/assetlinks.json (for FBG Android app)

- src/app.tsx
> Fix error found in console log in production: Cannot read property 'accept' of undefined

- blog/themes/next/_config.yml
- blog/themes/next/layout/_partials/header/brand.swig
> Improve blog links

- Dockerfile
Cache blog/ earlier on in Dockerfile
> Cache blog/ earlier on in Dockerfile

- src/App/Async.test.tsx
> Add tests for async

- src/games/chess/board.tsx
> Add chess board to game over screen

- package.json
- src/App/App.test.tsx
- src/App/Async.test.tsx
- src/App/Lobby/ListPlayers.tsx
- src/App/Lobby/NewRoom.test.tsx
- src/App/Lobby/Room.test.tsx
- yarn.lock
Update yarn.lock (which broke async tests), add react testing library, get async tests working
> Update yarn.lock (which broke async tests), add react testing library, get async tests working

- src/App/Game/GameSharing.test.tsx
- src/App/Game/GameSharing.tsx
Improve GameSharing test
Blocked by #391
> Improve GameSharing test

- src/App/Game/GameDarkSublayout.test.tsx
- src/App/Game/GameDarkSublayout.tsx
Rewrite tests / increase coverage for GameDarkSublayout
> Rewrite tests / increase coverage for GameDarkSublayout

- src/App/Game/GameModePicker.test.tsx
- src/App/Game/GameModePicker.tsx
> Rewrite GameModePicker test

- src/App/App.tsx
Routing: only allow valid gamemodes (ai, local)
> Routing: only allow valid gamemodes (ai, local)

- package.json
Add `yarn run test:changed:coverage:watch`
> Add yarn run test:changed:coverage:watch

- src/games/chess/board.test.tsx
- src/games/chess/board.tsx
> Increase coverage for Chess

- src/App/Lobby/LobbyService.test.tsx
- src/App/Lobby/LobbyService.ts
Increase test coverage in LobbyService.ts
> Increase test coverage in LobbyService.ts

- src/App/App.tsx
Reverts freeboardgame/FreeBoardGame.org#400
> Revert "Routing: only allow valid gamemodes (ai, local)"

- package.json
- yarn.lock
> Upgrade webpack, babel

- blog/yarn.lock
> Upgrade blog dependencies

- src/games.test.ts
- src/games/checkers/instructions.md
- src/games/cornerus/index.ts
- src/games/cornerus/instructions.md
- src/games/ninemensmorris/index.ts
- src/games/ninemensmorris/instructions.md
- src/games/reversi/index.ts
- src/games/reversi/instructions.md
- src/games/takesix/index.ts
- src/games/takesix/instructions.md
> Adding instructions to all games and adding tests that check that we have them

- src/App/Game/GameInstructions.test.tsx
- src/App/Game/GameInstructions.tsx
> Add GameInstructions.test.tsx

- src/App/Game/Enhancers/ReactGAEnhancer.test.ts
- test/test-setup.js
Improve tests for ReactGAEnhancer
> Improve tests for ReactGAEnhancer

- .huskyrc
- package.json
- yarn.lock
Fix husky running tests twice, upgrade various deps
> Fix husky running tests twice, upgrade various deps

- games/tictactoeplus/game.ts
The winner bug is solved.
Closes #424
> bug solved by returning winner

- .yarnrc
- components/App/Game/GameDarkSublayout.test.tsx
- components/App/Game/GameDarkSublayout.tsx
- components/App/Game/GameLayout.tsx
- games/checkers/board.tsx
- games/chess/board.tsx
- games/cornerus/board.tsx
- games/fourinarow/board.tsx
- games/ninemensmorris/board.tsx
- games/reversi/board.tsx
- games/seabattle/board.tsx
- games/takesix/board.tsx
- games/tictactoe/board.tsx
- games/tictactoeplus/board.tsx
> Display game name

- components/App/Game/GameSharing.tsx
Replace annoying alert() when clicking "copy link":
> Replace annoying alert() when clicking "copy link":

- pages/g/[gameCode]/index.tsx
Redirect /g/[gamecode] to /pages/[gamecode]
> Redirect /g/[gamecode] to /pages/[gamecode]

- components/App/Game/GameLayout.test.tsx
- components/App/Game/GameOver.tsx
- jest.unit.setup.ts
Fix "Play Again" button for AI/Local games when offline
Fixes #453
> Fix "Play Again" button for AI/Local games when offline

- components/App/MessagePageClass.tsx
- pages/room/[gameCode]/[roomID]/Room.tsx
Add reload button on "Failed to Fetch" page
Closes #466
> Add reload button on "Failed to Fetch" page

- webpack.server.config.js
Use worker-loader in webpack.server.config.js
> Use worker-loader in webpack.server.config.js

- src/games/reversi/board.test.tsx
- src/games/reversi/board.tsx
Fix Reversi game over in local mode
Fixes #437
> Fix Reversi game over in local mode

- src/components/App/Game/GameSharing.test.tsx
- src/components/App/Game/GameSharing.tsx
Remove email button from GameSharing due to lack of use
> Remove email button from GameSharing due to lack of use

- src/components/App/Game/GameInstructionsText.test.tsx
Improve test coverage for GameInstructionsText.test.tsx
> Improve test coverage for GameInstructionsText.test.tsx

- blog/source/_posts/Publishing-your-first-boardgame-io-game-in-FBG.md
This fixed the tutorial for me.
However, I was unable to see the blog when running the server myself - not sure if this is normal.
> update how to guide

- src/components/App/Game/GameOver.tsx
- src/games/takesix/board.test.tsx
Switch to data-testid for takesix board test
> Switch to data-testid for takesix board test

- src/pages/about.tsx
> add JvSomeren to contributors on about page

- blog/_config.yml
- blog/source/_posts/Whats-new-Apr-12-2020.md
- blog/themes/next/_config.yml
- blog/themes/next/layout/_macro/post.swig
> Add what's new post to blog, various blog changes

- package.json
> Fix yarn run dev

- src/games/takesix/board.tsx
> Fix takesix CSS issue

- package.json
- yarn.lock
> ugprading bgio

- Dockerfile
- blog/yarn.lock
Generate the blog with Node 13.13.0 because of #524.
> Generate the blog with Node 13.13.0 because of Hexo incompatibility with Node 14

- src/games/hangman/EnterWordPrompt.tsx
- src/games/hangman/board.tsx
Hangman: allow keyboard entry, remove extra ! from gameover ("you won!!")
> Hangman: allow keyboard entry, remove extra ! from gameover ("you won!!")

- blog/source/_posts/Whats-new-Apr-19-2020.md
Add "What's New, week of April 19" blog post
> Add "What's New, week of April 19" blog post

- src/games/hangman/board.tsx
- src/games/rota/Field.tsx
- src/games/rota/board.tsx
Small changes, 
- hangman hint fixed 
- rota gameover board
> hangman rota improved

- web/src/components/App/Game/GameSharing.test.tsx
> Increase test coverage for <GameSharing>

- web/src/games/index.ts
> Reoder games by popularity

- web/src/games/secretcodes/PlayBoard.tsx
- web/src/games/secretcodes/board.tsx
- web/src/games/secretcodes/game.ts
> Show the board at the end of the game (closes #542)

- web/src/games/checkers/board.tsx
- web/src/games/chess/config.ts
> Correct colors in Checkers, close #540

- web/jest.config.js
- web/src/components/DesktopMobileView.tsx
- web/src/games/index.ts
- web/src/misc/IsMobileContext.ts
- web/src/misc/UaContext.ts
- web/src/misc/UaHelper.test.ts
- web/src/misc/UaHelper.ts
- web/src/pages/_app.tsx
- web/src/pages/play/[gameCode]/GameInfo.tsx
> Avoid needlessly passing props

- fbg-server/src/match/MatchUtil.ts
- fbg-server/src/match/db/Match.entity.ts
- fbg-server/src/match/match.service.spec.ts
- fbg-server/src/rooms/RoomUtil.ts
- fbg-server/src/rooms/rooms.service.ts
> Fix backend by differentiating between internal/external bgio endpoints

- fbg-server/src/app.module.ts
- fbg-server/src/rooms/rooms.service.ts
> Temporary solution to reduce the likelihood of fbg-server hanging like it happened today

- fbg-server/package.json
- fbg-server/src/main.ts
- fbg-server/src/models/User.model.ts
- fbg-server/src/users/gql-auth-guard.ts
- fbg-server/src/users/users.resolver.ts
- fbg-server/src/util/logging.ts
- fbg-server/yarn.lock
- web/package.json
- web/server/logging.ts
- web/server/web.ts
- web/src/pages/room/[roomID]/Room.tsx
- web/yarn.lock
This will allow us to keep track of the server status and setup an alert if the server misbehaves like it did yesterday.
> Create logging infrastructure

- web/.storybook/webpack.config.js
> Handle CSS in storybook

- web/Dockerfile
- web/src/infra/common/services/LobbyService.ts
> Change keys for JWT local storage

- web/docs/WhyFbg.stories.mdx
- web/src/gamesShared/components/badges/PlayerBadges.stories.tsx
> Improving storybook

- web/server/web.ts
- web/src/infra/home/Header.tsx
- web/static/prodRobots.txt
> robots.txt in production to exclude /docs

- web/src/games/secretcodes/definitions.ts
- web/src/games/secretcodes/game.ts
Reworked the code where needed so that the tags could be removed.
> Remove @ts-ignore tags from Secret Codes.

- web/package.json
- web/src/deprecated-bgio-ui/2d/token.test.js
- web/src/games/secretcodes/PlayBoard.test.tsx
- web/src/games/secretcodes/PlayBoard.tsx
- web/src/games/secretcodes/definitions.ts
- web/src/games/secretcodes/game.test.ts
- web/src/games/secretcodes/game.ts
Secret Codes: Merge giveClue with Play phases, close #543
> Secret Codes: Merge giveClue with Play phases

- fbg-server/src/rooms/RoomUtil.ts
- fbg-server/src/rooms/gql/Lobby.gql.ts
- fbg-server/src/rooms/lobby.resolver.ts
- fbg-server/src/rooms/lobby.service.spec.ts
- fbg-server/src/rooms/lobby.service.ts
- fbg-server/src/rooms/rooms.module.ts
- fbg-server/src/rooms/rooms.resolver.ts
- fbg-server/src/rooms/rooms.service.ts
> Implementing lobby

- web/src/games/secretcodes/PlayBoard.tsx
- web/src/gamesShared/components/badges/PlayerBadges.stories.tsx
- web/src/gamesShared/components/badges/PlayerBadges.tsx
> Secret Codes: display a Spy emoji in the player badge (closes #587)

- web/src/games/takesix/board.tsx
> Remove automatic playing from takesix

- web/src/games/zooparade/components/bcardwithhint.tsx
> Fix numbers on Zooparade cards

- web/src/infra/lobby/NewRoomModal.tsx
> Fix leaking games in development on the lobby selection

- web/docs/NewGame.stories.mdx
> Fix tutorial, missing export default

- cli/test/test.js
- cli/test/test_game.js
> Allowing extra args for <yarn run test GAME>

- cli/genGames/cli.js
> Fixing gen:games

- web/src/infra/lobby/LobbyCarousel.css
- web/src/infra/lobby/LobbyCarousel.test.tsx
- web/src/infra/lobby/LobbyCarousel.tsx
> Fix message padding, improve wording of error message

- web/src/games/mergers/game.test.ts
Includes unit tests for the moves, and then three scenario tests including one that plays out an entire game on a small board.
> Add main game tests for Mergers

- helm/templates/bgio-deployment.yaml
- helm/templates/fbg-server-deployment.yaml
- helm/templates/web-deployment.yaml
- helm/values.yaml
> Updates helm replicas

- web/src/infra/game/Game.tsx
> Fix board cannot get matchID

- fbg-server/src/rooms/rooms.module.ts
- fbg-server/src/rooms/rooms.service.spec.ts
- fbg-server/src/rooms/rooms.service.ts
- fbg-server/src/users/users.module.ts
- fbg-server/src/users/users.resolver.ts
TODO:
- Fix "kicked out of the room" error 
- Add unit tests
> Fix for update user sync issue

- web/src/games/config.json
> Changing order of games to reflect stats.freeboardgames.org + soup of letters in first

- web/src/games/mergers/Board.css
- web/src/games/mergers/board.test.tsx
- web/src/games/mergers/board.tsx
- web/src/games/mergers/components/HotelGrid.css
- web/src/games/mergers/components/HotelGrid.tsx
- web/src/games/mergers/components/MergerDetails.css
- web/src/games/mergers/components/MergerDetails.test.tsx
- web/src/games/mergers/components/MergerDetails.tsx
- web/src/games/mergers/components/MergersDialog.tsx
- web/src/games/mergers/components/MergersGameStatus.tsx
- web/src/games/mergers/components/PlayerActions.css
- web/src/games/mergers/components/PlayerActions.test.tsx
- web/src/games/mergers/components/PlayerActions.tsx
- web/src/games/mergers/components/StockGuide.css
- web/src/games/mergers/components/StockGuide.tsx
- web/src/games/mergers/components/StockLabel.css
- web/src/games/mergers/components/StockLabel.tsx
- web/src/games/mergers/game.ts
This is the full working UI for Mergers. It's in pretty good shape with some room for improvement in a few areas.
Here's how I think it's doing against the release checklist:
- Only thing from the original game is the name of the hotel chains ("Tower", "American" etc.) which I'm happy to change if needed.
- This is borderline, curious to hear what other folks think. Tough to improve it much without introducing pan/zoom, although we could try rotating the grid 90 degrees on mobile.
- Good coverage of the rules. Decent coverage of the UI but I'd eventually like to add some more.
- I have a custom game over page. I see there's a shared component - should I try and use that one?
Mobile: 
Desktop:
> Add Mergers UI

- web/src/games/checkers/board.tsx
- web/src/games/chess/board.tsx
- web/src/games/tictactoe/board.tsx
- web/src/games/tictactoeplus/board.tsx
- web/src/gamesShared/helpers/GameUtil.ts
- web/src/infra/game/Match.tsx
> Enabling spectator view for tic-tac-toe

- web/src/games/seabattle/board.tsx
- web/src/games/soupofletters/board.tsx
- web/src/gamesShared/components/fbg/GameDarkSublayout.tsx
- web/src/gamesShared/components/fbg/GameLayout.tsx
> Fix scrolling issue for android devices on soup of letters and seabattle

- web/src/games/mergers/Board.css
- web/src/games/mergers/board.tsx
- web/src/games/mergers/components/HotelGrid.css
- web/src/games/mergers/components/HotelGrid.tsx
- web/src/games/mergers/components/PlayerActions.tsx
- web/src/games/mergers/components/StockLabel.css
- web/src/games/mergers/instructions.md
- Improves responsiveness and fixes issue where board gets cutoff on wide screens
- Adjusts colors to improve contrast and readability of tiles
- Changes from dashed outline to "+" label for available tiles
Mobile:
Desktop:
> Improve Mergers board layout

- web/src/games/mergers/Board.css
- web/src/games/mergers/components/PlayerActions.test.tsx
- web/src/games/mergers/components/PlayerActions.tsx
> Mergers: validate stock exchanges and tweak colors

- web/src/games/config.json
- web/src/games/mergers/index.ts
> Publish Mergers

- web/Dockerfile
copy story book build result to image
> fix story book

- web/src/games/memorymatch/index.ts
- web/src/games/memorymatch/instructions.md
Memory match game with a 5x5 grid ready to publish!
> set default grid size to 5x5

- web/src/games/secretDracula/board.tsx
- web/src/games/secretDracula/svgComponents/playerInfo.tsx
Revisited comments from Spooky, 
Added spectator view,
> Gkp sdracula final UI fix

- web/src/games/bingo/board.tsx
- web/src/games/bingo/components/callCard.tsx
- web/src/games/bingo/components/countDown.tsx
- web/src/games/bingo/game.test.ts
- web/src/games/bingo/game.ts
I tried playing bingo in PROD, but sometimes it worked and sometime it did not. 
I added a check for preventing timeRef update too early. 
Also added spectator view.
> Bingo bug fix

- web/src/games/soupofletters/board.test.tsx
- web/src/games/soupofletters/board.tsx
- web/src/games/soupofletters/game.ts
- web/src/games/soupofletters/games.test.ts
Timer improvements and spectator view
> Gkp sol spectator

- web/src/games/hangman/board.tsx
- web/src/games/memorymatch/board.tsx
- web/src/games/ninemensmorris/board.tsx
- web/src/games/reversi/board.tsx
So, I checked the spectator views for some of the games, 
specifically, 
memory match 
reversi 
secret codes 
hangman
> Gkp somemore spectator views

- web/src/infra/chat/Chat.module.css
- web/src/infra/chat/Chat.tsx
> Fix Chat mobile UX

- web/src/games/soupofletters/board.tsx
- web/src/games/soupofletters/game.ts
- web/src/games/soupofletters/soup.tsx
Following improvements in SOLetters, 
1. show current score in active game 
2. removed single point of failure in timer, this has 2 advantages: i) if a player leaves in between than others can continue playing - after time elapses, ii) I had a friend with an old hu**ei phone and on that phone the timer was actually firing after 30 to 40 seconds (the funny part is, it was eventually firing but not consistently).
> Soletters further improvements

- web/src/games/bullsAndCows/Board.module.css
- web/src/games/bullsAndCows/board.tsx
- web/src/games/bullsAndCows/config.ts
- web/src/games/bullsAndCows/game.ts
Just small updates as I was testing mobile UI, also I was finally able to remove the secret from the PlayerView, and still able to show on GameOver.
> fix Bulls and Cows mobile UI and hide secret from player View

- cli/test/test_all.js
> Mute console.error when running all tests

- fbg-server/src/rooms/rooms.service.spec.ts
- fbg-server/src/users/users.resolver.spec.ts
- fbg-server/src/users/users.service.spec.ts
- fbg-server/src/users/users.service.ts
- web/src/infra/common/components/auth/NicknamePrompt.tsx
> Limit nickname to 15 characters and alphanumerics

- web/src/games/secretDracula/board.tsx
- web/src/games/secretDracula/game.ts
Simply shows everything for endgame.
> show everything for endgame

- web/src/games/checkers/board.tsx
- web/src/games/checkers/game.test.ts
- web/src/games/checkers/game.ts
Giving these functions a more object-oriented face.
> Introduce "Coord" class in Checkers to group together related methods.

- README.md
- web/src/pages/about.tsx
Hi, I just added some credits for myself :P
> added credit info

- web/src/games/cardtable/CribbageBoardB.test.tsx
- web/src/games/cardtable/CribbageBoardB.tsx
* [X ] Use a separate branch in your local repo (not `master`).
* [X ] I've read and agree with the [contribution guidelines](https://www.freeboardgames.org/docs/?path=/story/documentation-contributing--page).
Fixes a defect in display logic for pegging 1 point from 119 to 120 (peg hole 60). 
Adding tests to cribbage board validating the behavior described in this defect.
> feature/cardtable patch for pegging defect. 

- web/src/games/soupofletters/board.tsx
- web/src/games/soupofletters/soup.tsx
Hi, in this PR the side horizontal bounce effect should now be disabled. 
For iphone, there is still a problem with vertical scroll, 
https://stackoverflow.com/questions/7768269/ipad-safari-disable-scrolling-and-bounce-effect
maybe this could be a solution for that.
> disabled side scroll

- web/src/games/tictactoeplus/game.ts
Hi, 
there was a minor bug in the tic-tac-toe-plus winning condition, 
If the last item to appear was a plus, then there is a possibility of draw in many cases (since there can be 2 winners) 
This has been covered.
> imporve tttplus win condition

- web/src/games/secretDracula/board.tsx
> Fixes #738

- web/src/games/bullsAndCows/service.test.ts
- web/src/games/bullsAndCows/service.ts
> fix #737 avoid duplicated hints for Bulls and Cows

- web/src/games/checkers/board.tsx
- web/src/games/checkers/coord.test.ts
- web/src/games/checkers/coord.ts
- web/src/games/checkers/game.test.ts
- web/src/games/checkers/game.ts
> Remove classes from checkers to avoid serialziation bugs

- web/src/games/bombsAndBunnies/game.ts
- web/src/games/bombsAndBunnies/tests/secretstate.test.ts
> added secret state to bombs and bunnies

- helm/Chart.yaml
- helm/templates/fbg-server-deployment.yaml
After changes on the liveness probe
> Upgrade helm

- fbg-server/src/main.ts
This will fix /healthz failing issue
> Disable CORS for localhost requests

- docker-build.sh
> Exit script if docker build fails

- web/jest.config.js
- web/jest.setup.ts
- web/src/test/setup/enzyme.ts
- web/src/test/setup/mockCopy.ts
- web/src/test/setup/mockFetch.ts
- web/src/test/setup/mockGa.ts
- web/src/test/setup/mockGameDarkSublayout.ts
- web/src/test/setup/mockI18next.ts
- web/src/test/setup/mockPlay.ts
- web/src/test/setup/mockRouter.ts
- web/src/test/setup/mockScrollTo.ts
- web/src/test/setup/mockSw.ts
- web/src/test/setup/mockWindowLocation.ts
- web/src/test/setup/supressWarn.ts
> [infra] Jest setup

- web/cypress/integration/mobile/MobileView.ts
- web/cypress/integration/tablet/404.ts
- web/cypress/integration/tablet/Meta.ts
- web/cypress/integration/tablet/TabletView.ts
- web/cypress/integration/tablet/TicTacToe.ts
- web/cypress/integration/tablet/playAGame.ts
- web/public/static/locales/en/ErrorPage.json
- web/src/pages/_error.tsx
> [i18n] Replace raw English texts on infra/pages components: ErrorPage

- web/public/static/locales/en/About.json
- web/src/pages/about.tsx
> [i18n] Replace raw English texts on infra/pages components: About

- web/public/static/locales/en/ConnectionLost.json
- web/src/infra/game/ConnectionLost.tsx
- web/src/infra/game/GameBoardWrapper.test.tsx
- web/src/infra/game/GameBoardWrapper.tsx
> [i18n] Replace raw English texts on infra/pages components: GameBoardWrapper

- web/public/static/locales/en/Game.json
- web/src/infra/game/Game.test.tsx
- web/src/infra/game/Game.tsx
- web/src/infra/game/LocalGame.tsx
Replace raw English text on Game component.
> refactor: replace raw English text: Game

- web/public/static/locales/en/Match.json
- web/src/infra/game/Match.test.tsx
- web/src/infra/game/Match.tsx
- web/src/test/utils/rtl.tsx
> refactor: replace raw English text: Match

- web/public/static/locales/en/NewRoomModal.json
- web/src/infra/lobby/NewRoomModal.tsx
> [i18n] replace raw English text: NewRoomModal

- web/public/static/locales/en/GameSharing.json
- web/src/infra/room/GameSharing.test.tsx
- web/src/infra/room/GameSharing.tsx
> [i18n] replace raw English text: GameSharing

- web/public/static/locales/en/QrCodePopup.json
- web/src/infra/room/QrCodePopup.test.tsx
- web/src/infra/room/QrCodePopup.tsx
> [i18n] replace raw English text: QrCodePopup

- web/public/static/locales/en/GameSharing.json
- web/public/static/locales/en/ListPlayers.json
- web/src/infra/room/GameSharing.test.tsx
- web/src/infra/room/GameSharing.tsx
- web/src/infra/room/ListPlayers.tsx
> [i18n] replace raw English text: ListPlayers

- web/public/static/locales/en/GameModePickerCard.json
- web/src/infra/gameInfo/GameInfo.tsx
- web/src/infra/gameInfo/GameModePickerCard.tsx
> [i18n] Translate remaining GameInfo component

- web/src/infra/game/GameProvider.tsx
Fixes the error below that started popping up after https://github.com/freeboardgames/FreeBoardGames.org/pull/845
> Fix dev error for async GameProvider

- web/public/static/locales/en/StartMatchButton.json
- web/src/infra/room/StartMatchButton.test.tsx
- web/src/infra/room/StartMatchButton.tsx
> [i18n] replace missing raw English text: StartMatchButton

- web/public/static/locales/en/CustomizationBar.json
- web/src/infra/settings/CustomizationBar.tsx
> [i18n] replace missing raw English text: CustomizationBar

- web/public/static/locales/en/OccupancySelect.json
- web/src/infra/common/components/game/OccupancySelect.tsx
> [i18n] replace raw English text: OccupancySelect

- web/public/static/locales/en/NicknamePrompt.json
- web/public/static/locales/en/NicknameRequired.json
- web/src/infra/common/components/auth/NicknamePrompt.test.tsx
- web/src/infra/common/components/auth/NicknamePrompt.tsx
- web/src/infra/common/components/auth/NicknameRequired.tsx
> [i18n] replace missing raw English text: NicknamePrompt and NicknameRequired

- web/public/static/locales/en/MessagePage.json
- web/src/infra/common/components/alert/MessagePage.test.tsx
- web/src/infra/common/components/alert/MessagePage.tsx
> [18n] replace raw English text: MessagePage

- web/public/static/locales/en/Chat.json
- web/src/infra/chat/Chat.tsx
> [i18n] replace raw English text: Chat

- web/public/static/locales/en/GameOver.json
- web/public/static/locales/en/Scoreboard.json
- web/src/gamesShared/components/fbg/GameOver.test.tsx
- web/src/gamesShared/components/fbg/GameOver.tsx
- web/src/gamesShared/components/scores/Scoreboard.tsx
- web/src/infra/gameInfo/GameModePicker.test.tsx
- web/src/infra/i18n/components/Link.test.tsx
- web/src/infra/lobby/LobbyCarousel.test.tsx
> [i18n] replace raw English text on Chat and Scoreboard

- web/src/games/zooparade/instructions.md
For the zoo parade game
Resolves the non-controversial issues in #866
* [x ] Use a separate branch in your local repo (not `master`).
* [x ] I've read and agree with the [contribution guidelines](https://www.freeboardgames.org/docs/?path=/story/documentation-contributing--page).
> Fix typos and grammar in instructions.md

- web/src/games/chess/index.ts
- web/src/games/chess/instructions.md
- web/src/games/chess/locales/en.json
- web/src/games/tictactoeplus/locales/en.json
- web/src/games/zooparade/index.ts
- web/src/games/zooparade/instructions.md
- web/src/games/zooparade/locales/en.json
- web/src/infra/redirects/play/generate.ts
From now on, we should only use the locales files to change the description of a (partially or fully) translated game - and possibly change or request others to make the same change on other available languages for that game.
> [i18n] Use descriptive values from locales/en.json on GameDef

- web/src/games/tictactoeplus/board.test.tsx
- web/src/games/tictactoeplus/board.tsx
Fixing the mess I made while trying to merge the last PR
> Fix tictactoeplus tests

- web/src/games/chess/index.ts
- web/src/games/chess/locales/pt.json
> [i18n] finish chess translation to pt

- web/src/games/bingo/board.test.tsx
- web/src/games/bingo/board.tsx
- web/src/games/bingo/components/callCard.tsx
- web/src/games/bingo/definitions.ts
- web/src/games/bingo/index.ts
- web/src/games/bingo/instructions.md
- web/src/games/bingo/locales/en.json
> [i18n] refactor: replace raw English text on bingo

- web/docs/GameTranslation.stories.mdx
- web/src/gamesShared/components/animation/AutoHide.stories.tsx
- web/src/gamesShared/components/animation/Blink.stories.tsx
- web/src/infra/common/components/game/GameCard.tsx
- web/src/infra/gameInfo/GameInfo.tsx
Closes #884 
- fix: make HMR/live-reload work properly on storybook
- i18n: add docs
- i18n: add translation docs link
> [i18n] Translation docs

- web/docs/1.GameTranslation.stories.mdx
- web/docs/2.AddingNewLanguage.stories.mdx
- web/src/infra/redirects/play/paths.ts
> [i18n] add docs about how to add a new language

- web/server/config/i18n/sync/copyOnce.ts
- web/src/games/soupofletters/board.test.tsx
- web/src/games/soupofletters/board.tsx
- web/src/games/soupofletters/index.ts
- web/src/games/soupofletters/instructions.md
- web/src/games/soupofletters/locales/en.json
> [i18n] soupofletters

- fbg-server/package.json
- fbg-server/src/app.module.ts
- fbg-server/src/migration/1622004228093-NewRoomIndexes.ts
- fbg-server/src/rooms/db/Room.entity.ts
- fbg-server/src/rooms/db/RoomMembership.entity.ts
Context: Our `fbg-server` service is slowing down and becoming unresponsive, failing its liveness check and restarting multiple times in a short period of time almost every morning (PST time). This started about ~ 1 mo ago, and initially required me to manually restart the server. I implemented the liveness check that is mitigating the issue (degraded service but no perceived downtime), but this is not sustainable, as the problem is becoming worse and happening more frequently. The issue is correlated with high usage of the website, only happening in the mornings on PST time where we get more than 1,500 players in less than an hour. This PR tries to improve the performance with some low-hanging fruit optimizations of the query used for the liveness check and tackle some possible …
> Small optimizatiosn to improve fbg-server performance

- helm/Chart.yaml
- helm/templates/bgio-deployment.yaml
- helm/templates/fbg-server-deployment.yaml
- helm/templates/web-deployment.yaml
- helm/values.yaml
In order to reduce CPU throttling which I think is the culprit of the recent issues we were having.
> Update helm charts requests and limits

- fbg-server/src/healthz.controller.ts
- helm/templates/fbg-server-deployment.yaml
> Increases timeout from 2s to 5s for fbg-server

- web/src/games/secretcodes/Lobby.tsx
- web/src/games/secretcodes/LobbyPlayer.tsx
- web/src/games/secretcodes/LobbyTeam.tsx
- web/src/games/secretcodes/PlayBoard.test.tsx
- web/src/games/secretcodes/PlayBoard.tsx
- web/src/games/secretcodes/board.test.tsx
- web/src/games/secretcodes/board.tsx
- web/src/games/secretcodes/customization.tsx
- web/src/games/secretcodes/index.ts
- web/src/games/secretcodes/instructions.md
- web/src/games/secretcodes/locales/en.json
> refactor: replace raw English text on secretcodes

- web/src/games/bingo/index.ts
- web/src/games/bingo/locales/pt.json
- web/src/games/secretDracula/index.ts
- web/src/games/secretDracula/locales/pt.json
- web/src/games/secretcodes/index.ts
- web/src/games/secretcodes/locales/pt.json
- web/src/games/soupofletters/index.ts
- web/src/games/soupofletters/locales/pt.json
- web/src/games/takesix/index.ts
- web/src/games/takesix/locales/pt.json
- web/src/games/zooparade/index.ts
- web/src/games/zooparade/locales/pt.json
> Translates bingo, secretDracula, secret codes, soup of letters, taksix

- web/.eslintrc.js
- web/src/infra/common/components/base/FreeBoardGamesBar.tsx
Adds a language selector to the top bar:
> Add language selector

- web/public/static/prodRobots.txt
- web/src/games/checkers/index.ts
> Small improvements to robot.txt and checkers video

- web/docs/RunningOnKubernetes.stories.mdx
- web/docs/RunningWithNginx.stories.mdx
- web/server/web.ts
> Adds nginx documentation

- web/src/gamesShared/components/fbg/GameDarkSublayout.tsx
- web/src/infra/common/components/base/FreeBoardGamesBar.tsx
> Fixes black background issue

- web/server/sitemap/encode.ts
> Restores sanitize

- .env
- backuper/Dockerfile
- backuper/backup.sh
- docker-build.sh
- fbg-server/src/app.module.ts
- helm/Chart.yaml
- helm/templates/backuper-cronjob.yaml
- helm/templates/fbg-server-deployment.yaml
- helm/values.yaml
> Creates fbg-backuper

- backuper/backup.sh
- helm/templates/backuper-cronjob.yaml
> Small backuper improvements

- CODE_OF_CONDUCT.mmd
> Creates code of conduct

- web/src/games/checkers/board.test.tsx
- web/src/games/checkers/board.tsx
This should make it easier for new players who might not understand why some tokens cannot be selected. It also makes the game a bit faster.
Preview: https://drive.google.com/file/d/1-sPZN4MuLXD0XObg0e8i22RZvXoFqdrt/view?usp=sharing
_(please ignore the eternity it takes me to plan my moves)_
> Pre-select board tokens in checkers when there is only 1 valid move.

- web/src/games/picnicGo/board.tsx
- web/src/games/picnicGo/components/Hand.tsx
- web/src/games/picnicGo/components/PlayerInfo.tsx
- web/src/games/picnicGo/components/stylesheet.module.css
- web/src/games/picnicGo/game.test.ts
- web/src/games/picnicGo/game.ts
- web/src/games/picnicGo/types.ts
This should fix every issue brought up in #957 - the game now uses a different confirmation system independent of ctx which fixes the bug we've been having, all G and ctx handlers should now be typed, and new unit tests have been added. It also adds more UI implementations, though it's still far from complete.
This should be the last gameplay-related PR for this game - I haven't identified any additional bugs with the game, so work should now be able to fully begin on a functional UI.
> Picnic Go: more game refactoring + unit test

- helm/templates/web-deployment.yaml
> Improves web liveness check

- web/src/deprecated-bgio-ui/2d/token.js
> Fixes token warning on drag and drop

- web/.storybook/main.js
- web/.storybook/preview.js
- web/package.json
- web/yarn.lock
* [ X] Use a separate branch in your local repo (not `master`).
* [ X] I've read and agree with the [contribution guidelines](https://www.freeboardgames.org/docs/?path=/story/documentation-contributing--page).
Adds a viewport control that switches between common portal sizes for handheld devices --
> adding @storybook/addon-viewport support

- web/src/gamesShared/components/cards/Card.stories.tsx
- web/src/gamesShared/components/cards/Card.tsx
By request from @cwatsonc, this displays a notification if the card value is out of the range of supported values for the `<Card />` component.
Furthermore, the card stories are updated to respect that only one of width and height can be specified at once.
> Card: notify if value is out of range

- web/package.json
- web/src/games/chess/ai.ts
- web/src/games/chess/stockfish8.worker.d.ts
- web/src/test/setup/mockI18next.ts
- web/yarn.lock
This is the start of a long-haul effort to bring as many of our dependencies up to date as possible.
As of now, only typescript will be upgraded. Other dependencies will come in later PRs.
> Upgrade typescript to 4.5

- web/src/games/secretDracula/board.tsx
- web/src/games/secretDracula/locales/en.json
- web/src/games/secretDracula/phases/vote/phase.ts
This PR improves some strings and okay button click experience.
> Improved translated sting errors and okay button click tracking

- web/src/games/picnicGo/game.ts
- web/src/infra/game/hooks/useConfigBuilder.tsx
@vdfdev, would you please deploy this on Freeboardgames.org to see whether the statistics change somehow? It shouldn't be noticable for the user at all.
> picnicGo: use Math.random as seed

- web/src/infra/room/Room.tsx
> Removes discord link from lobby

- misc/fbg-autoupdate/README
- misc/fbg-autoupdate/update
> Improves auto-updater to also update helm

- web/src/games/chess/locales/de.json
- web/src/games/chess/locales/en.json
- web/src/games/chess/locales/it.json
- web/src/games/chess/locales/pt.json
- web/src/games/fourinarow/locales/pt.json
- web/src/games/seabattle/locales/de.json
- web/src/games/seabattle/locales/en.json
- web/src/games/secretcodes/locales/de.json
- web/src/games/secretcodes/locales/en.json
- web/src/games/secretcodes/locales/pt.json
- web/src/games/takesix/locales/de.json
- web/src/games/takesix/locales/en.json
- web/src/games/takesix/locales/pt.json
- web/src/games/tictactoe/locales/de.json
- web/src/games/tictactoe/locales/en.json
- web/src/games/tictactoe/locales/pt.json
- web/src/games/tictactoeplus/locales/de.json
- web/src/games/tictactoeplus/locales/en.json
- web/src/games/tictactoeplus/locales/pt.json
I noticed that we had a typo in most of the translated json files while breaking lines.
It should be `\n\n` instead of `\\\n`. 
Eg: [view-source:https://www.freeboardgames.org/pt/jogar/jogo-da-velha](view-source:https://www.freeboardgames.org/pt/jogar/jogo-da-velha)
See the screenshot which shows a `\` in every line break:
> i18n(): replace \\\n with \n\n

- web/src/games/seabattle/index.ts
- web/src/games/seabattle/locales/pt.json
> translate(seabattle): PT

- web/src/games/memorymatch/board.test.tsx
- web/src/games/memorymatch/board.tsx
- web/src/games/memorymatch/customization.tsx
- web/src/games/memorymatch/index.ts
- web/src/games/memorymatch/instructions.md
- web/src/games/memorymatch/locales/en.json
- web/src/games/memorymatch/locales/pt.json
> translate(memorymatch): PT

- web/src/games/seabattle/index.ts
> fix(seabattle): fix code to batalha-naval to improve SEO

- web/src/games/picnicGo/index.ts
- web/src/games/picnicGo/locales/pt.json
- web/src/infra/lobby/NewRoomModal.tsx
> translate(picnicGo): PT

- misc/e2e/main.ts
> Updates e2e test to also work on dev instances

- web/src/games/ninemensmorris/board.tsx
- web/src/games/ninemensmorris/index.ts
- web/src/games/ninemensmorris/instructions.md
- web/src/games/ninemensmorris/locales/en.json
- web/src/games/ninemensmorris/locales/pt.json
> translation(ninemensmorris): setup translation and translated to PT

- web/docs/01_getting_started/3.NewGame.stories.mdx
- web/src/games/mancala/Shapes.tsx
- web/src/games/mancala/board.test.tsx
- web/src/games/mancala/board.tsx
- web/src/games/mancala/constants.ts
- web/src/games/mancala/game.ts
- web/src/games/mancala/index.ts
- web/src/games/mancala/instructions.md
- web/src/games/mancala/locales/en.json
- web/src/games/mancala/locales/pt.json
- web/src/games/reversi/locales/pt.json
Migrate from Enzyme to rtl for mancala
> translate(mancala): setup i18n and translate to PT

- web/src/games/cornerus/board.tsx
- web/src/games/cornerus/index.ts
- web/src/games/cornerus/instructions.md
- web/src/games/cornerus/locales/en.json
- web/src/games/cornerus/locales/pt.json
> translate(cornerus): setup i18n and translate to PT

- web/src/games/checkers/board.tsx
Right now, the component uses a mixes of vanilla functions and lambdas for its helpers, which is a bit confusing. This PR standardizes it to use just lambdas.
> Standardize helper functions in checker's Board component to all use lambdas.

- web/src/games/checkers/board.tsx
Another attempt to catch incorrect calls at compile time.
Also removed the `step` property since it was unused.
> Explicitly define the type for checker's move functions.

- web/package.json
- web/yarn.lock
> upgrades bgio

- cli/codegen/cli.js
- cli/codegen/codegen.js
- cli/codegen/genGames.js
- cli/dev/cli.js
- cli/dev/dev.js
- cli/fix/fix.js
- cli/fix/fix_all.js
- cli/fix/fix_game.js
- cli/lint/lint.js
- cli/lint/lint_all.js
- cli/lint/lint_game.js
- cli/test/test.js
- cli/test/test_all.js
- cli/test/test_game.js
- cli/util.js
- package.json
- web/package.json
- yarn.lock
> Upgrade chalk

- .github/workflows/automerge.js.yml
Most of the time I dont have anyone to ask review for, and I still want to be able to auto-merge my PRs, so I am changing so the bot approves the PR for me.
> Creates auto-approval flow

- .github/dependabot.yml
> adds web to dependabot

- v2/fbg-games/games.json
- v2/fbg-games/tictactoe/game.yaml
- v2/fbg-web/infra/games/GameLoader.ts
- v2/fbg-web/infra/games/GameSummaryParser.ts
- v2/fbg-web/package.json
- v2/fbg-web/pages/index.tsx
- v2/yarn.lock
> Renders home page based on games.json and game.yaml

- misc/fbg-autoupdate/update
> Prune docker images after updating prod

- .github/workflows/ci.js.yml
- v2/fbg-web/.eslint.json
- v2/fbg-web/.prettierignore
- v2/fbg-web/infra/games/GameDetailsParser.ts
- v2/fbg-web/infra/games/GameLoader.ts
- v2/fbg-web/infra/games/GameSummaryParser.ts
- v2/fbg-web/infra/games/GameTranslationsParser.ts
- v2/fbg-web/infra/i18n/I18nConfigLoader.ts
- v2/fbg-web/infra/i18n/I18nConfigParser.ts
- v2/fbg-web/infra/i18n/I18nGetGameId.ts
- v2/fbg-web/next-i18next.config.js
- v2/fbg-web/next.config.js
- v2/fbg-web/package.json
- v2/fbg-web/pages/[lang]/[playVerb]/[gameCode]/index.tsx
- v2/fbg-web/pages/[lang]/index.tsx
- v2/fbg-web/pages/_app.tsx
- v2/fbg-web/pages/index.tsx
- v2/package.json
- v2/yarn.lock
> Adds lint to v2

- .github/workflows/ci.js.yml
- v2/fbg-web/infra/games/GameDetailsParser.test.ts
- v2/fbg-web/infra/games/GameDetailsParser.ts
- v2/fbg-web/infra/games/GameSummaryParser.test.ts
- v2/fbg-web/infra/games/GameSummaryParser.ts
- v2/fbg-web/infra/games/GameTranslationsParser.test.ts
- v2/fbg-web/infra/games/GameTranslationsParser.ts
- v2/fbg-web/jest.config.js
- v2/fbg-web/package.json
- v2/package.json
- v2/yarn.lock
> Setup jest for v2

- v2/fbg-games/gamesShared/components/fbg/FreeBoardGamesBar.tsx
- v2/fbg-games/gamesShared/components/fbg/GameOver.tsx
- v2/fbg-web/pages/[lang]/[playVerb]/[gameCode]/local/index.tsx
- v2/fbg-web/public/locales/de/GameOver.json
- v2/fbg-web/public/locales/en/GameOver.json
- v2/fbg-web/public/locales/pt/GameOver.json
> [v2] Creates initial game over page

- v2/fbg-web/infra/widgets/GameInstructionsText.tsx
- v2/fbg-web/pages/[lang]/[playVerb]/[gameCode]/index.tsx
> [v2] Small improvements to GameInfo

- .github/workflows/github-page.js.yml
> Fixes triggerfor github page deploy

- .github/workflows/automerge.js.yml
- .github/workflows/github-page.js.yml
> Disable auto-auto-merge because of issues with CI not triggering

- v2/fbg-games/gamesShared/components/fbg/FreeBoardGamesBar.tsx
- v2/fbg-games/gamesShared/components/fbg/GameOver.tsx
- v2/fbg-web/infra/widgets/GameCard.module.css
- v2/fbg-web/infra/widgets/GameCard.tsx
- v2/fbg-web/infra/widgets/GameInstructionsText.tsx
- v2/fbg-web/pages/[lang]/[playVerb]/[gameCode]/index.module.css
- v2/fbg-web/pages/[lang]/[playVerb]/[gameCode]/index.tsx
- v2/fbg-web/pages/[lang]/index.module.css
- v2/fbg-web/pages/[lang]/index.tsx
- v2/fbg-web/public/locales/de/Home.json
- v2/fbg-web/public/locales/en/Home.json
- v2/fbg-web/public/locales/pt/Home.json
> [v2] Adds Home to v2

- v2/fbg-games/gamesShared/components/fbg/FreeBoardGamesBar.tsx
- v2/fbg-web/pages/[lang]/index.module.css
- v2/fbg-web/pages/[lang]/index.tsx
- v2/fbg-web/pages/index.tsx
> [v2] Shows how many games each language has, and small improvements

- v2/fbg-web/infra/widgets/FbgMetaButtons.module.css
- v2/fbg-web/infra/widgets/FbgMetaButtons.tsx
- v2/fbg-web/pages/[lang]/about.module.css
- v2/fbg-web/pages/[lang]/about.tsx
- v2/fbg-web/pages/index.module.css
- v2/fbg-web/pages/index.tsx
- v2/fbg-web/public/locales/de/About.json
- v2/fbg-web/public/locales/en/About.json
- v2/fbg-web/public/locales/pt/About.json
> [v2] Create new about page

- v2/fbg-games/gamesShared/components/customization/Dropdown.tsx
- v2/fbg-games/gamesShared/components/customization/Slider.tsx
- v2/fbg-games/tictactoe/ai.ts
- v2/fbg-games/tictactoe/customization.tsx
- v2/fbg-web/infra/misc/gameStaticPaths.ts
- v2/fbg-web/pages/[lang]/[playVerb]/[gameCode]/ai/index.tsx
> [v2] Makes AI work

- v2/fbg-games/gamesShared/definitions/customization.ts
- v2/fbg-games/tictactoe/ai.ts
- v2/fbg-web/infra/alert/LoadingMessage.tsx
- v2/fbg-web/infra/alert/MessagePage.tsx
- v2/fbg-web/infra/alert/SvgError.tsx
- v2/fbg-web/infra/settings/CustomizationBar.tsx
- v2/fbg-web/infra/settings/GameCustomization.ts
- v2/fbg-web/infra/settings/SettingsService.tsx
- v2/fbg-web/pages/[lang]/[playVerb]/[gameCode]/ai/index.tsx
- v2/fbg-web/pages/[lang]/[playVerb]/[gameCode]/index.tsx
> [v2] Implements quick customization

- v2/fbg-games/gamesShared/components/fbg/GameOver.tsx
- v2/fbg-web/infra/alert/AlertLayer.module.css
- v2/fbg-web/infra/alert/AlertLayer.tsx
- v2/fbg-web/infra/alert/LoadingMessage.tsx
- v2/fbg-web/infra/alert/MessagePage.tsx
- v2/fbg-web/infra/alert/SvgError.tsx
- v2/fbg-web/infra/settings/CustomizationBar.tsx
- v2/fbg-web/infra/settings/GameCustomization.ts
- v2/fbg-web/infra/settings/SettingsService.tsx
- v2/fbg-web/infra/widgets/GameModePicker.tsx
- v2/fbg-web/pages/[lang]/[playVerb]/[gameCode]/ai/index.tsx
- v2/fbg-web/pages/[lang]/[playVerb]/[gameCode]/local/index.tsx
- v2/fbg-web/public/locales/de/GameInfo.json
- v2/fbg-web/public/locales/en/GameInfo.json
- v2/fbg-web/public/locales/pt/GameInfo.json
> [v2] Finishes single player/offline modes.

- v2/fbg-bgio/main.ts
- v2/tsconfig.json
> [v2] Habemus backend!

- v2/fbg-bgio/main.ts
- v2/fbg-bgio/package.json
- v2/fbg-server
- v2/fbg-web/infra/hooks/useServer.ts
- v2/yarn.lock
> [v2] Creates graceful shutdown for server.

- v2/fbg-web/infra/hooks/useLogin.ts
- v2/fbg-web/infra/hooks/useServer.ts
- v2/fbg-web/pages/[lang]/[playVerb]/[gameCode]/online/index.tsx
> [v2] Creates useLogin hook

- v2/fbg-web/infra/hooks/useLogin.ts
- v2/fbg-web/infra/widgets/NicknamePrompt.module.css
- v2/fbg-web/infra/widgets/NicknamePrompt.tsx
- v2/fbg-web/pages/[lang]/[playVerb]/[gameCode]/local/index.tsx
- v2/fbg-web/pages/[lang]/[playVerb]/[gameCode]/online/index.tsx
- v2/fbg-web/public/locales/de/LoadingMessage.json
- v2/fbg-web/public/locales/de/NicknamePrompt.json
- v2/fbg-web/public/locales/en/LoadingMessage.json
- v2/fbg-web/public/locales/en/NicknamePrompt.json
- v2/fbg-web/public/locales/pt/LoadingMessage.json
- v2/fbg-web/public/locales/pt/NicknamePrompt.json
> [v2] Creates login page for logged off users.

- .github/pull_request_template.md
- README.md
- web/docs/02_how_to/1.GameTranslation.stories.mdx
- web/src/infra/common/components/game/GameCard.tsx
- web/src/infra/gameInfo/GameInfo.tsx
> fix broken doc links

- .github/dependabot.yml
- v2/fbg-games/gamesShared/components/fbg/FreeBoardGamesBar.tsx
- v2/fbg-games/gamesShared/components/fbg/GameDarkSublayout.tsx
- v2/fbg-web/infra/games/GameDetailsParser.test.ts
- v2/fbg-web/infra/widgets/FbgMetaButtons.tsx
- v2/fbg-web/infra/widgets/GameContributors.tsx
- v2/fbg-web/infra/widgets/GameModePicker.tsx
- v2/fbg-web/package.json
- v2/fbg-web/pages/[lang]/index.tsx
- v2/fbg-web/pages/index.tsx
- v2/yarn.lock
> [v2] Update to Next13

- web/src/games/cardtable/ACardTable.tsx
- web/src/games/cardtable/CardContainer.tsx
- web/src/games/cardtable/CribbageBoard.test.tsx
- web/src/games/cardtable/CribbageBoard.tsx
- web/src/games/cardtable/game.ts
> adding egocentric views
