freeboardgames/FreeBoardGames.org

package-lock.json

> **The merge.recursive function in the merge package v <1.2 can be tricked into adding or modifying properties of the Object prototype. These properties will be present on all objects allowing for a denial of service attack.**
https://nvd.nist.gov/vuln/detail/CVE-2018-16469

Update merge dependency

---

.travis.yml

0afe10c34b1834a0834bb9d7a0fc2ed4426e25f9 and our old node version on Travis-CI is making CI fail.
https://travis-ci.com/freeboardgame/FreeBoardGame.org/builds/99573941
CI passes with the newer node version.

Use a newer node version for Travis-CI

---

src/App/MessagePageClass.tsx

Remove target="_blank" from Go Home button so home doesn't open in a new window.

Remove target="_blank" from Go Home button so home doesn't open in a new window.

---

src/App/Game/GameModePicker.test.tsx
src/App/Game/GameModePicker.tsx
src/games/index.tsx
src/games/tictactoe/ai.test.ts
src/games/tictactoe/ai.ts
src/games/tictactoe/config.ts

Add easy AI to TicTacToe
---
The current AI for TicTacToe uses BGIO's MCTS, and it does not let users win.
This PR adds an easy "AI" which makes moves randomly. 
The easy AI is now the default, and the MCTS AI remains as the "hard" option.
A dropdown for selecting the difficulty was also added as IGameModeExtraInfoDropdown.

Add easy AI to TicTacToe

---

.travis.yml
README.md

Revert "Remove .travis.yml (#151)"
Reverting back to Travis because we originally switched to Semaphore thinking there were issues with Travis (turned out to be a jest bug), and Semaphore does not pass the necessary information to Coveralls for it to leave a comment with coverage information.

Switch back to TravisCI

---

src/games/chess/board.tsx

Chess: Highlight squares for the last move (closes #55)
@flamecoals, this works in multiplayer mode but does not work well with AI.  I suspect that async is the problem, can you help?  Also, what color should we make the highlighted square?

Chess: Highlight squares for the last move

---

src/index.html
src/metadata.test.ts
src/metadata.ts
src/server.tsx

Use meta noindex tag instead of robots.txt
https://support.google.com/webmasters/answer/93710?hl=en
If running on freeboardgame.org, return 404 for /robots.txt, else, return a restrictive robots.txt
Closes #192

Use meta noindex tag instead of robots.txt

---

src/App/Game/GameDarkSublayout.tsx

Before the homepage link was large and had 100% width (red).  Now it only surrounds the FBG logo / text.  This fixes the BGIO debugging tools and will also help me implement #195.

Fix appbar -- now link is only surrounding the FBG logo / text.

---

src/games/seabattle/Battle.test.tsx

Fix 'Not implemented: HTMLMediaElement ...' warnings when running tests

Fix 'Not implemented: HTMLMediaElement ...' warnings when running tests

---

@types/react-easy-i18n/index.d.ts
@types/ts-easy-i18n/index.d.ts
package.json
src/About/About.tsx
src/App/App.tsx
src/App/MessagePageClass.tsx
test/test-setup.js
yarn.lock

Switch to ts-easy-i18n
I don't like the idea of using react-easy-i18n's <Text> components.  It can sometimes make things (like passing translations to components) tricky. 
Instead we can now use ```{ trans('home.header') }```  :-)

Switch to ts-easy-i18n

---

test/test-setup.js

Fix 'Not implemented: window.scrollTo' warning in tests

Fix 'Not implemented: window.scrollTo' warning in tests

---

src/App/MessagePageClass.test.tsx
src/App/MessagePageClass.tsx

Fixes
```Warning: Can’t call setState on an unmounted component. This is a no-op, but it indicates a memory leak in your application. To fix, cancel all subscriptions and asynchronous tasks in the componentWillUnmount method.```

Fix memory leak in MessagePage

---

src/typings.d.ts

Fix TS warning: Arbitrary expressions are forbidden in export assignments in ambient contexts
https://github.com/Microsoft/TypeScript/wiki/Breaking-Changes#arbitrary-expressions-are-forbidden-in-export-assignments-in-ambient-contexts

Fix TS warning: Arbitrary expressions are forbidden in export assignments in ambient contexts

---

package.json

Re-add `yarn run precommit` command accidentally removed in prior commit

Re-add `yarn run precommit` command accidentally removed in prior commit

---

src/App/Lobby/NewRoom.test.tsx
src/App/Lobby/NewRoom.tsx

Do not create a new room when back button is pressed on game lobby page
Fixes #374

Do not create a new room when back button is pressed on game lobby page

---

webpack.server.config.js

Exclude workers in webpack.server.config.js
Dramatic difference in server build time:
Before:
```
server_bgio.js  29.7 MiB       0  [emitted]  server_bgio
server_web.js  29.8 MiB       1  [emitted]  server_web     
Done in 26.35s.                                                                                                                                                                               
```
After:
``` 
server_bgio.js   5.3 MiB       0  [emitted]  server_bgio
server_web.js  5.32 MiB       1  [emitted]  server_web 
Done in 2.96s.                                                                                 
```

Exclude workers in webpack.server.config.js

---

fbg-server/src/rooms/RoomUtil.ts
fbg-server/src/rooms/rooms.service.spec.ts
fbg-server/src/rooms/rooms.service.ts

This makes so the creator of the room is always the first player on the list, which is the assumption made by Secret codes.

Keep the join order on rooms

---

web/src/games/hangman/board.css
web/src/games/hangman/board.test.tsx
web/src/games/hangman/board.tsx
web/src/games/hangman/util.test.ts
web/src/games/hangman/util.ts

The table displays the score for each player on the GameOver screen as well as between turns.
#490 
Preview:
Between turns
End of game

Add score table to Hangman.

---

web/src/infra/common/components/game/GameCard.tsx

This eliminates comments/spaces in SSR of the name of games:
```html
<h2 ...>Play Chess</h2>
```

Eliminate comments/spaces in SSR rendering

---

.gitattributes
web/src/games/zooparade/components/bbuttons.tsx
web/src/games/zooparade/components/bcard.tsx
web/src/games/zooparade/components/bcardwithhint.tsx
web/src/games/zooparade/components/bhinticon.tsx

The numbers on cards and stuff should display as 1-5 to the user, not 0-4. #620 went some way towards this, but doesn't seem to have had the desired effect. This change fixes this, the way I assumed it would be done when I was working on the code before. I have reverted the internal logic to use 0-4, made sure cards and hints only _display_ 1-5.
This means:
- The large numbers on the cards now show 1-5 (even after #620, they showed 0-4).
- Hints aren't kinda broken (they were before, become some of the logic was using 1-5 while the rest of it still expected 0-4).
The fact that the internal logic used 0-4 is an wierd characteristic of the code that should probably be documented to that people don't make the intuitive - but sadly buggy - changes as in #620 (thankfully @Spooky-0 warned me …

Fixed Numbering Throughout Zoo Parade

---

fbg-server/Dockerfile
web/Dockerfile

Current docker image contains yarn package cache and unused dev dependencies.
They are redundant for running in prod.

Optimize docker image size by using alpine as base

---

fbg-server/Dockerfile
web/Dockerfile

The images are crashing in loop now:
Error on the fbg-server pod:
```
yarn run v1.22.5
$ cross-env NODE_ENV=production node dist/main
internal/modules/cjs/loader.js:883
throw err;
^
Error: Cannot find module '/appdata/dist/main'
at Function.Module._resolveFilename (internal/modules/cjs/loader.js:880:15)
at Function.Module._load (internal/modules/cjs/loader.js:725:27)
at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:72:12)
at internal/main/run_main_module.js:17:47 {
code: 'MODULE_NOT_FOUND',
requireStack: []
}
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```
Error on the web and bgio pod:
```
/bin/sh: ./docker_run.sh: not found
```
Reverts freeboardgames/FreeBoardGames.org#680

Revert "Optimize docker image size by using alpine as base"

---

web/src/games/mergers/components/MergersDialog.tsx

Uses the example here: https://material-ui.com/components/dialogs/#draggable-dialog

Make Mergers dialogs draggable

---

web/src/games/mergers/components/PlayerActions.test.tsx
web/src/games/mergers/components/PlayerActions.tsx
web/src/games/mergers/game.test.ts
web/src/games/mergers/game.ts

Prevented negative input for buying and swapping/selling, in the backend and frontend.

Don't allow negative input in Mergers

---

web/src/games/bingo/game.ts

The game was not declaring victory for all horizontal rows, it was doing it only for first row

Updated Bingo horizontal victory condition

---

web/src/games/mergers/Board.module.css

Hiding the chat box makes the header disappear. This fixes that by changing the padding to margin, and adjusts the height and overflow-y of the container since the scroll bar is now unnecessary on the board component.
Before:
After:

Fix Mergers header

---

web/src/infra/chat/internal/ChatMessage.tsx

Fix `<ChatMessage>`: Anonymous functions cause React's Fast Refresh to not preserve the component's state.

Fix ChatMessage.tsx: Anonymous functions cause React's Fast Refresh to not preserve the component's state.

---

web/src/infra/lobby/GameCardWithOverlay.tsx
web/src/infra/lobby/NewRoomModal.tsx
web/src/infra/room/Room.tsx

| Scenarios | Result | Evidence |
| -- | -- | -- |
| When clicking on an existing public room | `/:lang/room/:id` | https://user-images.githubusercontent.com/2018161/116763153-3833d480-a9f3-11eb-9689-a8d129d26a55.mp4 |
| When creating a public room | `/:lang/room/:id` | https://user-images.githubusercontent.com/2018161/116763162-4681f080-a9f3-11eb-84f4-006d057e916e.mp4 |
| When creating a new room | gets `roomID` properly | https://user-images.githubusercontent.com/2018161/116763706-c9577b00-a9f4-11eb-95ed-dcf3a1545697.mp4 |
| When starting a match | `/:lang/match/:id` | same than before |
| When leaving a room | `/:lang/` | same than before |

[i18n] replace usage of next/router for infra/i18n (part. 4)

---

web/src/infra/game/AIOrLocalGame.tsx
web/src/infra/i18n/hooks/useHref.ts
web/src/infra/i18n/utils/href.ts
web/src/infra/i18n/utils/router.ts
web/src/infra/room/GameSharing.test.tsx
web/src/infra/room/GameSharing.tsx
web/src/pages/_app.tsx
web/src/pages/about.tsx
web/src/pages/g/[gameCode]/index.tsx
web/src/pages/match/[matchId]/index.tsx
web/src/pages/play/index.tsx
web/src/pages/room/[roomID]/[catchAll]/index.tsx
web/src/pages/room/[roomID]/index.tsx

- Replace next/router for infra/i18n for some redirects on /play, /room, /g.
- Replace next/router for infra/i18n for SEO Breadcrumbs (because of pathname).
- Replace onRouteChangeComplete for a subscription of a listener on a specific event: `routeChangeComplete` (see https://stackoverflow.com/a/53933774).
- Translate shareable room link by making `translateHref` function also call `lngPathCorrector` - which is an internal function from next-i18next.
These changes should finish all required changes to make navigation compliant to i18n :tada:

[i18n] change next/router for infra/i18n (part. 5) 

---

web/jest.config.js
web/jest.setup.defineProperty.ts
web/package.json
web/public/static/locales/en/GameCard.json
web/public/static/locales/en/GameInfo.json
web/public/static/locales/en/chess.json
web/public/static/locales/pt/GameCard.json
web/public/static/locales/pt/GameInfo.json
web/public/static/locales/pt/chess.json
web/server/sitemap/sitemap.test.ts
web/src/gamesShared/components/fbg/GameLayout.test.tsx
web/src/infra/common/components/game/GameCard.tsx
web/src/infra/game/GameProvider.tsx
web/src/infra/gameInfo/GameInfo.tsx
web/src/infra/i18n/components/Link.test.tsx
web/src/infra/i18n/hocs/index.ts
web/src/infra/i18n/hocs/withNewT.tsx
web/src/infra/i18n/hocs/withTranslate.tsx
web/src/infra/i18n/types/index.ts
web/src/infra/i18n/utils/index.ts
web/src/infra/i18n/utils/mix.ts
web/src/infra/room/GameSharing.test.tsx
web/src/pages/_app.tsx

Propose a game translation structure, which provides a way to translate the game definition (name, description, text instructions, and video id instructions). The game code is not being translated here yet.
- Each game has a file named with its code (e.g. `public/static/locales/en/chess.json`) - each language needs a file like this one.
- In case of a game does not have a translating file, it will fallback for the content located where the game is defined (e.g. `src/games/chess/index.ts`).
- `withTranslate` is a decorator which knows how to translate string which are specific for a game (not only its definitions). The game is obtained from pages where `gameCode` is a path param. Also, on those pages and inner components, you could use `useCurrentGame` to have access to the `gameDef` …

[i18n] Game translation structure

---

web/src/gamesShared/definitions/customization.ts
web/src/infra/settings/CustomizationBar.tsx

The proposal here is to deprecate `renderQuick` and `renderFull`, used by customization. 
**Why?** Currently, it isn't possible to use hooks or HOCs directly inside those render methods because they are not components, only returns React elements. As an alternative, a second component that wraps everything returned by a render method would be necessary. Using a `useCurrentGameTranslation` or `withCurrentGameTranslation` is necessary to translate customization, like [this one](https://github.com/freeboardgames/FreeBoardGames.org/blob/137424c4d24f28d1e6bddce7a51975f2c47b3480/web/src/games/tictactoeplus/customization.tsx#L25).
**What is coming in?** I'm proposing that a component (or multiple) be provided as customization. The signature is pretty similar, but by letting React handle the …

[i18n] Deprecate render methods used by customizations

---

web/src/games/ninemensmorris/game.ts

Don't end the placement phase if a player has to remove a piece. The consequence of this bug is that control switches players too early when a mill is formed in the final turn of the placement phase. Hence, the wrong player's piece is removed.
Improve comments for Nine Men's Morris.
This pertains to #901. It is a conservative change, but I am skeptical that it fully addresses the issue since the placement phase also ends too early, and control incorrectly switches players if the 17th piece to be placed creates a mill.

Correct bug in gameplay of Nine Men's Morris.

---

web/src/games/bombsAndBunnies/board.tsx
web/src/games/estatebuyer/board.tsx
web/src/games/frenchTarot/board.tsx
web/src/games/mergers/board.tsx
web/src/games/secretcodes/board.tsx
web/src/games/takesix/board.tsx
web/src/games/zooparade/board.module.css
web/src/games/zooparade/board.tsx
web/src/gamesShared/components/fbg/GameDarkSublayout.tsx
web/src/gamesShared/components/fbg/GameLayout.tsx

This implements the changes proposed in #922:
1. For the component `<GameLayout />`, the boolean property `allowWiderScreen` is replaced by the string property `maxWidth` so that the width can be adjusted more freely. As before, the maximum width defaults to `500px`. I modified all games that currently use the `allowWiderScreen` property so that nothing changes for them (i.e. maximum width is `1000px` in that case).
2. The vertical centering in the component `<GameDarkSublayout />` was broken, and is now fixed. The game board is still centered vertically and the average user will probably notice nothing. But when the screen height is very low, the board is prevented from overlapping on the top like in the following screenshots:
The above screenshots show the behavior *before* this PR. …

GameDarkSublayout: maxWidth and vertical centering

---

web/src/games/secretDracula/phases/vote/phase.ts

This on endIf is causing a infinite loop on newer versions of BGIO

Moves setActivePlayers out of endIf to onMove

---

helm/templates/bgio-deployment.yaml
helm/templates/fbg-server-deployment.yaml
helm/templates/web-deployment.yaml
helm/values.yaml

Due to [this bug](https://medium.com/omio-engineering/cpu-limits-and-aggressive-throttling-in-kubernetes-c5b20bd8a718), Kubernetes was throttling most services. Removing the limits fixed it.  This will make our http responses come ~25% faster.

Removes limits from helm chart deployments

---

web/src/games/schafkopf/components/GameBoard.tsx
web/src/games/schafkopf/game.ts
web/src/games/schafkopf/tests/util.ts
web/src/games/schafkopf/types.ts
web/src/games/schafkopf/util/misc.ts
web/src/games/schafkopf/util/placement.ts

This fixes a little UI problem and adds a "called player runs away" rule to the Schafkopf game for 4 players: There are no "official" rules for this game, but typically, there are restrictions in which situations the called player is allowed to play the called suit (i.e., "run away"), especially the Ace.
There are more rule variants for Schafkopf, especially for the round scoring, but I felt like this one is the most important missing from the current implementation. Furthermore, the UI problem made the game unplayable in some situations (with a React error message on the screen).

Update Schafkopf rules

---

web/server/config/i18n/sync/copy.ts

`mkdir` and `cp` do not work on Windows as-is because they take different formats there. For instance, `mkdir` on Windows uses `-Force` instead of `-p`. Using Node calls should make the script OS-agnostic.

Replace mkdir and cp in copy.ts with native Node calls.

---

web/src/games/checkers/board.tsx

Previously, I was pre-selecting a coordinate on `_move`. It turns out this is only called in the React world by drag and click events. AI calls moves directly. Thus, `componentDidUpdate` is a better place for this calculation.
Preview: https://drive.google.com/file/d/105i5haOXtGZW30yc4EmwGr6iAxjyeCEJ/view?usp=sharing

Recalculate pre-selected token on checkers state change to account for AI moves.

---

web/src/gamesShared/components/scores/Scoreboard.stories.tsx
web/src/gamesShared/components/scores/Scoreboard.tsx

This allows the `Scoreboard` component to be extended with as many additional columns as necessary per game. I've also implemented a visible example with storyboard. Hopefully, it shouldn't be too hard to figure out what this is supposed to do based on the example I provided.
Feel free to merge if everything looks good as it is, but I do have two points I'd like to raise:
- Right now, all the extra components are listed between the player name and the score. Should this be moved after the score instead?
- There's currently no check to ensure that `extraData` and `extraColumns` are the same length. I admit that I don't know how to make react throw an error properly here, but I'm not sure how necessary that check is, since the columns would obviously look misaligned anyways if there's a …

Make Scoreboard component extensible

---

web/src/games/picnicGo/board.tsx

After some playtesting with my friends, it seems there's a problem that occurs when multiple players make a move at nearly the same time, where one of the moves will fall through, and the player would need to click again for the move to properly register. After studying Take Six's code (which is another game with simultaneous turns), I've decided to follow its example and try making the move functions asynchorous to see if this would fix the problem.
This is not a tested patch, as I unfortunately don't have any way to test out making moves on multiple players at the same time - however, at the very least, this does not break any existing functionality, so in the worst case scenario, this commit does nothing. In the best case, though, this should fix the strange "lag" issue that's been …

Picnic Go: make move functions in board async

---

web/src/games/checkers/board.test.tsx
web/src/games/checkers/board.tsx
web/src/games/checkers/customization.tsx
web/src/games/checkers/game.test.ts
web/src/games/checkers/game.ts
web/src/games/checkers/index.ts
web/src/games/checkers/instructions.md
web/src/games/checkers/locales/en.json
web/src/games/checkers/locales/pt.json

This adds, well, a lot of improvements to checkers, the biggest change being the new customization interface. If fully implemented, this should fully close both #604 and #946.
Please read through the list of changes carefully, as I've went ahead and made some changes that may be controversial - I can revert any changes that is believed to be a bad idea.
- Rewrote all of `board.tsx` into a functional component, rather than a class component. React hooks are used to replicate all the functions of a class component's state, so functionally, this should be practically identical to before.
- Migrated all text to use the translate function. This is made possible by the functional component rewrite above. Please note two things about this change:
- Despite the game already having locale files …

Checkers: A lot of general improvements, new customization settings

---

web/src/games/checkers/board.tsx
web/src/games/checkers/game.test.ts
web/src/games/checkers/game.ts

This PR does a few big things:
- The `G` object has been optimized a little - instead of storing the entire board, it now only stores where all the pieces are. This should functionally behave identically to before, but it should slightly reduce both the amount of looping required and the amount of data sent back and forth between server and client.
- There's now a new function that will create a board from a string, and `INITIAL_BOARD` now reads from these strings rather than a full array. This, once again, should be functionally identical to before, but it allows for...
- New unit tests have been added. The new `convertStringToBoard` function allows for testing from a much wider variety of positions without needing to manually define where each piece is in the board array, and I've …

Checkers: Minor improvements, new unit tests

---

web/src/games/checkers/board.tsx
web/src/games/checkers/game.test.ts
web/src/games/checkers/game.ts

This PR does two things:
- Fixed a bug with the game end logic. I've also added a new unit test that should check for this in the future.
<details>
<summary>Details of the bug</summary>
Consider this position:
After white takes the forced capture, white technically has no moves left (it's up against the edge, and its only square forward is blocked by two pieces). However, it should now be black's move, which means the game shouldn't end quite yet. With the former logic using `endIf`, the game would incorrectly end immediately after this move, since the game detects that white no longer has any moves remaining, but doesn't account for whose turn it is after the move.
To fix this, I've simply moved the valid moves check to `onBegin`, and added a safety return to `board.tsx` to handle an …

Checkers: Bugfix, piece deselecting

---

web/src/games/sixtysix/board.tsx
web/src/games/sixtysix/game.ts
web/src/games/sixtysix/locales/de.json
web/src/games/sixtysix/moves.ts
web/src/games/sixtysix/types.ts
web/src/games/sixtysix/util/misc.ts
web/src/gamesShared/components/cards/PlayerZones.tsx

After playing this game for a few rounds, we found that the melds ("marriages") of players are not correctly displayed on the opponent's screen, and melds wouldn't expire after each round. So, this small PR fixes this.

sixtysix: fix displayed melds

---

web/src/games/mergers/Board.module.css
web/src/games/mergers/board.test.tsx
web/src/games/mergers/board.tsx
web/src/games/mergers/components/HotelGrid.module.css
web/src/games/mergers/components/HotelGrid.tsx
web/src/games/mergers/components/MergersGameStatus.module.css
web/src/games/mergers/components/MergersGameStatus.tsx
web/src/games/mergers/components/PlayerActions.module.css
web/src/games/mergers/components/PlayerActions.tsx
web/src/games/mergers/components/StockGuide.tsx
web/src/games/mergers/components/StockLabel.module.css
web/src/games/mergers/customization.tsx
web/src/games/mergers/game.test.ts
web/src/games/mergers/game.ts
web/src/games/mergers/hotels.ts
web/src/games/mergers/index.ts
web/src/games/mergers/types.ts
web/src/games/mergers/utils.ts

Adds a new mode where all players can see everyone's cash and stocks, in a table view. This mode is probably preferred for a lot of folks because all of the information in the game is public and trackable anyway, meaning if you just write down all the moves you can compute available cash and stocks for everyone.
In order to make the experience more consistent between modes, redesigns the regular mode view to use the same table, except with only one row showing your own state.
Switch (with details on hover):
Mobile (tested on a bunch of dimensions):
Desktop:
When not showing all hands:
Also:
- Switches buttons to "primary" color
- Fixes spelling of "Worldlywise'

[Mergers] Add mode where all player state is visible

---

web/src/games/mergers/game.test.ts
web/src/games/mergers/game.ts

The move uses state that is hidden by playerView. This is currently broken.

[Mergers] Do not run declareGameOver on the client

---

web/src/games/picnicGoTest/board.tsx
web/src/games/picnicGoTest/config.ts
web/src/games/picnicGoTest/game.ts
web/src/games/picnicGoTest/index.ts

As discussed on Discord, this adds an unlisted game with status "IN_DEVELOPMENT" that serves as a playground of picnic go card statistics on Freeboardgames.org
I tested this functionality locally, and everything works as expected.

Add test playground for picnic go stats

---

web/src/games/bashni/board.tsx
web/src/games/checkers/board.tsx
web/src/gamesShared/components/boards/Checkerboard.tsx

Using
```typescript
const [selected, setSelected] = React.useState(null)
```
makes the TS compiler treat `selected` as being of type `any`. That is error prone (the compiler might not catch us calling a non-existing member) and it also makes autocomplete harder during development.
Also explicitly set `algebraicToCartesian`'s return type since the compiler can't infer that the object obeys the `ICartesianCoords` interface.

Add a bit more type information to functions/React states that use ICartesianCoords

---

fbg-server/src/chat/chat.service.spec.ts
fbg-server/src/chat/chat.service.ts

Exactly what it says on the tin: this completely disables the swear filter for private matches while still having it work in public games.
Manual testing indicates this works for both the room and match screens, but we're still missing automated tests.

Disable swear filter for private matches
